export const APP_VERSION="21.0.0";
export const RULESET_VERSION="LUMBAR-RULESET-1.1.0";
export const SYNTHETIC_MODEL_VERSION="SYNTHETIC-RULE-EMULATOR-3.0.0";
export const EVIDENCE_VERSION="2026-07-31";
export const EXPORT_SCHEMA_VERSION="2.0.0";
