export const APP_VERSION="25.0.0";
export const RULESET_VERSION="LUMBAR-RULESET-1.3.0";
export const SYNTHETIC_MODEL_VERSION="SYNTHETIC-RULE-EMULATOR-3.0.0";
export const EVIDENCE_VERSION="2026-08-03";
export const EXPORT_SCHEMA_VERSION="4.0.0";
