export type Laterality = "not-assessed" | "right" | "left" | "bilateral" | "midline";
export type Root = "L1" | "L2" | "L3" | "L4" | "L5" | "S1";
export type MotorGrade = "5" | "4+" | "4" | "3" | "2" | "1" | "0" | "not-tested";
export type Reflex = "normal" | "reduced" | "absent" | "brisk" | "not-tested";
export type Severity = "none" | "mild" | "moderate" | "severe" | "not-graded";
export type ClinicalStatus = "present" | "absent" | "unknown" | "not-assessed";
export type LumbarLevel = "L1-2" | "L2-3" | "L3-4" | "L4-5" | "L5-S1";
export type LevelFinding = {
  level: LumbarLevel;
  central: Severity;
  rightRecess: Severity;
  leftRecess: Severity;
  rightForamen: Severity;
  leftForamen: Severity;
  discMorphology: "none" | "bulge" | "protrusion" | "extrusion" | "sequestration";
  migration: "none" | "cranial" | "caudal";
  synovialCyst: boolean;
  rootDeformation: boolean;
  priorDecompression: boolean;
};
export type CaseInput = {
  age:number|null; symptomDurationWeeks:number|null; onset:"not-assessed"|"acute"|"subacute"|"chronic"; side:Laterality;
  painPattern:"not-assessed"|"radicular"|"claudication"|"axial"|"mixed"|"uncertain"; suspectedRoot:Root|"none"|"multiroot";
  backPain:number|null; legPain:number|null; walkingLimitMeters:number|null; standingProvokes:boolean; sittingRelieves:boolean; flexionRelieves:boolean;
  coughSneezeProvokes:boolean; nightRestPain:boolean; groinPain:boolean; patientGoal:string;
  mostImportantSymptom:"not-assessed"|"leg-pain"|"back-pain"|"weakness"|"numbness"|"walking"|"other";
  desiredActivity:string; treatmentPreference:"nonoperative"|"surgery-open"|"undecided"; riskTolerance:"not-assessed"|"low"|"moderate"|"high";
  workDemand:"not-assessed"|"sedentary"|"light"|"moderate"|"heavy"|"retired"; homeSupport:"adequate"|"limited"|"unknown";
  odi:number|null; promisPhysicalFunction:number|null; promisPainInterference:number|null; depressionTScore:number|null; zcqSeverity:number|null;

  rightHipFlexion:MotorGrade; leftHipFlexion:MotorGrade; rightKneeExtension:MotorGrade; leftKneeExtension:MotorGrade;
  rightAnkleDorsiflexion:MotorGrade; leftAnkleDorsiflexion:MotorGrade; rightGreatToeExtension:MotorGrade; leftGreatToeExtension:MotorGrade;
  rightPlantarFlexion:MotorGrade; leftPlantarFlexion:MotorGrade;
  weaknessQuality:"true"|"pain-limited"|"give-way"|"uncertain"; weaknessTrajectory:"none"|"stable"|"progressive"|"improving";
  weaknessDurationDays:number|null; muscleAtrophy:boolean; examConfidence:"high"|"moderate"|"low";
  rightPatellarReflex:Reflex; leftPatellarReflex:Reflex; rightAchillesReflex:Reflex; leftAchillesReflex:Reflex;
  rightSensoryRoot:Root|"none"|"non-dermatomal"|"not-tested"; leftSensoryRoot:Root|"none"|"non-dermatomal"|"not-tested";
  sensoryRoot:Root|"none"|"non-dermatomal"|"not-tested";
  straightLegRaise:"positive"|"negative"|"not-tested"; femoralStretch:"positive"|"negative"|"not-tested";
  gaitAbnormal:boolean; heelWalkAbnormal:boolean; toeWalkAbnormal:boolean; repeatedHeelRaiseAbnormal:boolean;
  hipExamAbnormal:boolean; pulsesAbnormal:boolean; neuropathyFeatures:boolean;
  standingProvocationPattern:"not-assessed"|"standing"|"walking"|"both"; reliefPattern:"not-assessed"|"sitting"|"flexion"|"stopping-only"|"none";
  bicycleToleranceBetter:boolean; uphillBetter:boolean; legHeaviness:boolean;

  imagingAgeMonths:number|null; actualImagesReviewed:boolean; imageQuality:"adequate"|"limited"|"unknown"; levelByLevelDocumented:boolean;
  imagingMatrix:LevelFinding[]; imagingLevel:LumbarLevel|"multilevel"; imagingSide:"right"|"left"|"bilateral"|"central";
  imagingFinding:"disc"|"central-stenosis"|"lateral-recess"|"foraminal"|"extraforaminal"|"other"; stenosisSeverity:"mild"|"moderate"|"severe"|"not-graded";
  migratedDisc:boolean; spondylolisthesis:boolean; slipMillimeters:number|null; slipType:"none"|"degenerative"|"isthmic"|"high-grade";
  dynamicInstability:"unknown"|"absent"|"present"; translationMillimeters:number|null; angularMotionDegrees:number|null;
  deformityPresent:boolean; coronalCobbDegrees:number|null; lateralListhesisMillimeters:number|null; segmentalKyphosisDegrees:number|null; sagittalImbalancePresent:boolean;
  foraminalCollapse:"unknown"|"absent"|"present"; priorLumbarSurgery:boolean; priorLongFusion:boolean; plannedFacetResection:"unknown"|"limited"|"substantial";

  completedExerciseProgram:boolean; exerciseWeeks:number|null; medicationTrial:boolean;
  injectionResponse:"not-tried"|"none"|"brief"|"meaningful-temporary"|"sustained"; injectionLevel:"unknown"|LumbarLevel; injectionSide:"unknown"|"right"|"left"|"bilateral";
  injectionDurationDays:number|null; injectionType:"unknown"|"transforaminal"|"interlaminar"|"caudal"|"selective-root";
  injectionImmediateReliefPercent:number|null; injectionDelayedReliefPercent:number|null; injectionFunctionImproved:boolean;

  progressiveWeaknessStatus:ClinicalStatus; urinaryRetentionStatus:ClinicalStatus; urinarySensationLossStatus:ClinicalStatus; urinaryInitiationDifficultyStatus:ClinicalStatus; overflowIncontinenceStatus:ClinicalStatus;
  urgencyAlone:boolean; saddleAnesthesiaStatus:ClinicalStatus; bilateralSevereDeficitStatus:ClinicalStatus; feverStatus:ClinicalStatus; cancerWarningStatus:ClinicalStatus; traumaWarningStatus:ClinicalStatus; reducedAnalTone:"not-assessed"|"normal"|"reduced";
  postVoidResidualMl:number|null; fever:boolean; bacteremiaOrRecentInfection:boolean; immunosuppression:boolean; recentProcedure:boolean;
  cancerHistory:boolean; unexplainedWeightLoss:boolean; recentTrauma:boolean; osteoporosisRisk:boolean; chronicSteroidUse:boolean; inflammatoryFeatures:boolean;

  smoking:boolean; smokingStatus:"not-assessed"|"never"|"former"|"current"; cigarettesPerDay:number|null; packYears:number|null; quitDate:string; vapingNicotine:boolean; smokelessTobacco:boolean; nicotineReplacement:boolean;
  diabetes:boolean; diabetesType:"not-assessed"|"none"|"type-1"|"type-2"|"other"; a1c:number|null; a1cDate:string; insulinUse:boolean; bmi:number|null; frailty:"none"|"mild"|"moderate"|"severe"|"unknown"; clinicalFrailtyScale:number|null;
  boneHealth:"normal"|"osteopenia"|"osteoporosis"|"unknown"; priorFragilityFracture:boolean; dexLowestTScore:number|null; vitaminD:number|null; boneMedication:"none"|"antiresorptive"|"anabolic"|"unknown";
  chronicOpioidUse:boolean; opioidMmed:number|null; opioidDurationMonths:number|null; benzodiazepineUse:boolean; depressionAnxietyConcern:boolean; phq9:number|null; gad7:number|null;
  anticoagulation:boolean; anticoagulantName:string; priorDvtPe:boolean; anemia:boolean; hemoglobin:number|null; albumin:number|null; recentWeightLoss:boolean;
  hypertension:boolean; coronaryDisease:boolean; heartFailure:boolean; arrhythmia:boolean; copd:boolean; sleepApnea:boolean; cpapUse:boolean; kidneyDiseaseStage:"not-assessed"|"none"|"1"|"2"|"3"|"4"|"5"|"dialysis"; liverDisease:boolean; cardiopulmonaryDisease:boolean;
  priorSurgeryType:"not-assessed"|"none"|"decompression"|"discectomy"|"fusion"|"instrumentation"|"multiple"; priorSurgeryLevels:string; priorSurgeryDate:string; sameLevelRevision:boolean; priorDuralTear:boolean; priorInfection:boolean; priorPseudarthrosis:boolean; hardwareFailure:boolean;
  plannedProcedure:"not-selected"|"decompression"|"discectomy"|"fusion"|"decompression-fusion"|"other"; sexAtBirth:"unknown"|"female"|"male"|"intersex"; plannedLevels:number|null; plannedApproach:"not-selected"|"posterior"|"anterior"|"lateral"|"combined"; plannedRevision:boolean; plannedSetting:"outpatient"|"inpatient"|"not-selected";

  pediatric:boolean; pregnant:boolean; cervicalThoracicSymptoms:boolean; neuromuscularDisease:boolean; tumorKnown:boolean; infectionKnown:boolean; acuteFractureKnown:boolean;
  clinicianAgreement:"not-reviewed"|"agree"|"partly-agree"|"disagree"; overrideReasonCategory:"none"|"incorrect-syndrome"|"incorrect-level"|"incorrect-root"|"imaging-overcalled"|"imaging-undercalled"|"competing-diagnosis"|"deficit-severity"|"urgency"|"treatment-threshold"|"patient-preference"|"medical-risk"|"missing-information"|"other"; overrideReason:string; finalClinicalDecision:string;
};
export type EvidenceRef={id:string;title:string;source:string;year:number;note:string;population:string;limitations:string};
export type RuleTrace={ruleId:string;finding:string;basis:string;strength:"high"|"moderate"|"limited"|"consensus"};
export type CandidateTarget={level:string;side:string;root:string;zone:string;score:number;for:string[];against:string[]};
export type Applicability={status:"appropriate"|"limited"|"out-of-scope";reasons:string[]};
export type DecisionOutput={
 urgency:"routine"|"urgent"|"emergency"; urgencyReason:string; syndrome:string; neurologicSeverity:"none"|"mild"|"moderate"|"severe"|"indeterminate";
 reconciliation:"concordant"|"partially-concordant"|"discordant"|"insufficient"; reconciliationNarrative:string;
 applicability:Applicability; candidateTargets:CandidateTarget[]; support:string[]; contradictions:string[]; missing:string[]; alternatives:string[];
 diagnosticNextSteps:string[]; nonoperativePathway:string[]; surgicalDecision:string[]; fusionAssessment:string; operativeOptions:string[];
 surgicalPrerequisites:string[]; operativeRisks:string[]; optimization:string[]; patientGoalAlignment:string; riskSummary:string[];
 ruleTrace:RuleTrace[]; evidenceIds:string[]; checks:{label:string;status:"met"|"review"|"missing";rationale:string}[];
};
const n=(v:number|null, fallback=0):number=>v===null?fallback:v;
const measured=(v:number|null):v is number=>v!==null&&Number.isFinite(v);

export const EVIDENCE:EvidenceRef[]=[
 {id:"NASS-LDH",title:"Lumbar Disc Herniation With Radiculopathy",source:"North American Spine Society",year:2012,note:"Clinical and imaging correlation is required; no single examination finding is definitive.",population:"Adults with lumbar disc herniation and radiculopathy.",limitations:"Guideline predates some contemporary trials and techniques."},
 {id:"NASS-LSS",title:"Degenerative Lumbar Spinal Stenosis",source:"North American Spine Society",year:2011,note:"Stenosis is a clinical syndrome; imaging severity alone does not establish causation.",population:"Adults with degenerative lumbar stenosis.",limitations:"Evidence quality varies by intervention and outcome."},
 {id:"NORDSTEN-5Y",title:"Nordsten-DS Five-Year Randomized Trial",source:"BMJ",year:2024,note:"Decompression alone was non-inferior to decompression plus fusion for many patients with stenosis and degenerative spondylolisthesis.",population:"Selected patients with stenosis and degenerative spondylolisthesis.",limitations:"Does not apply automatically to high-grade, isthmic, deformity, destructive, or clearly unstable pathology."},
 {id:"SWEDISH-LSS",title:"Swedish Spinal Stenosis Study Five-Year Results",source:"Bone & Joint Journal",year:2024,note:"Routine fusion did not improve five-year disability outcomes in the studied population.",population:"Patients undergoing surgery for lumbar stenosis with or without low-grade slip.",limitations:"Individual anatomy and instability mechanisms still require assessment."},
 {id:"ACR-LBP",title:"Appropriateness Criteria: Low Back Pain",source:"American College of Radiology",year:2021,note:"Imaging and escalation depend on red flags, prior care, and intended intervention.",population:"Adults with low back pain and related symptoms.",limitations:"Appropriateness guidance does not replace direct clinical evaluation."},
 {id:"CES-PATH",title:"Suspected Cauda Equina Emergency Pathway",source:"National emergency pathway",year:2025,note:"Retention, loss of urinary sensation, saddle change, or severe bilateral deficit warrants emergency assessment.",population:"Patients with suspected cauda equina compression.",limitations:"Symptoms are imperfect; local emergency pathways and direct examination govern care."},
 {id:"CNS-RISK",title:"Preoperative Spine Risk Assessment",source:"CNS/AANS",year:2021,note:"Modifiable risks such as smoking, diabetes, nutrition, anemia, and bone health should be assessed separately from appropriateness.",population:"Patients considered for spine surgery.",limitations:"Risk magnitude varies by procedure and data source."}
];
const roots:Record<LumbarLevel,{exit:Root;trav:Root}>={"L1-2":{exit:"L1",trav:"L2"},"L2-3":{exit:"L2",trav:"L3"},"L3-4":{exit:"L3",trav:"L4"},"L4-5":{exit:"L4",trav:"L5"},"L5-S1":{exit:"L5",trav:"S1"}};
const sev=(x:Severity)=>x==="severe"?3:x==="moderate"?2:x==="mild"?1:0;
const grade=(g:MotorGrade):number|null=>g==="5"?5:g==="4+"?4.5:g==="4"?4:g==="3"?3:g==="2"?2:g==="1"?1:g==="0"?0:null;
function motorDeficit(i:CaseInput){const vals=[i.rightHipFlexion,i.leftHipFlexion,i.rightKneeExtension,i.leftKneeExtension,i.rightAnkleDorsiflexion,i.leftAnkleDorsiflexion,i.rightGreatToeExtension,i.leftGreatToeExtension,i.rightPlantarFlexion,i.leftPlantarFlexion].map(grade).filter((x):x is number=>x!==null);return vals.length?Math.min(...vals):null}
const abnormalSensory=(x:CaseInput["rightSensoryRoot"])=>x!=="none"&&x!=="not-tested";
const abnormalReflex=(x:Reflex)=>x==="reduced"||x==="absent"||x==="brisk";
function neurologicSeverity(i:CaseInput):DecisionOutput["neurologicSeverity"]{const m=motorDeficit(i);const progress=i.progressiveWeaknessStatus==="present";const bilateral=i.bilateralSevereDeficitStatus==="present";const testedSensory=i.rightSensoryRoot!=="not-tested"||i.leftSensoryRoot!=="not-tested";const testedReflex=[i.rightPatellarReflex,i.leftPatellarReflex,i.rightAchillesReflex,i.leftAchillesReflex].some(x=>x!=="not-tested");const testedFunctional=i.heelWalkAbnormal||i.toeWalkAbnormal||i.repeatedHeelRaiseAbnormal;const anyExam=m!==null||testedSensory||testedReflex||testedFunctional;if(!anyExam)return"indeterminate";if(progress||(m!==null&&m<=3)||bilateral)return"severe";if(m===4||testedFunctional)return"moderate";if(m===4.5||abnormalSensory(i.rightSensoryRoot)||abnormalSensory(i.leftSensoryRoot)||[i.rightPatellarReflex,i.leftPatellarReflex,i.rightAchillesReflex,i.leftAchillesReflex].some(abnormalReflex))return"mild";return"none"}
function scope(i:CaseInput):Applicability{const r:string[]=[];if(i.age===null) r.push("Age is not entered; applicability is indeterminate.");if(i.pediatric||(i.age!==null&&i.age<18))r.push("Pediatric patient");if(i.pregnant)r.push("Pregnancy-related evaluation");if(i.cervicalThoracicSymptoms)r.push("Predominant cervical or thoracic symptoms");if(i.neuromuscularDisease)r.push("Neuromuscular disease");if(i.tumorKnown||i.infectionKnown||i.acuteFractureKnown)r.push("Known tumor, infection, or acute fracture");if(i.priorLongFusion)r.push("Prior long-segment fusion or complex revision anatomy");if(i.slipType==="high-grade"||i.slipType==="isthmic")r.push("High-grade or isthmic spondylolisthesis");if(i.deformityPresent&&(measured(i.coronalCobbDegrees)&&i.coronalCobbDegrees>=20||i.sagittalImbalancePresent))r.push("Major deformity");if(i.painPattern==="axial")r.push("Predominantly axial pain is outside the operative recommendation scope");return r.length?{status:r.some(x=>x.includes("Known")||x.includes("Pediatric")||x.includes("cervical")||x.includes("Neuromuscular"))?"out-of-scope":"limited",reasons:r}:{status:"appropriate",reasons:[]}}
function candidates(i:CaseInput):CandidateTarget[]{const out:CandidateTarget[]=[];for(const f of i.imagingMatrix){const zones:[string,Severity,string,string][]=[["right lateral recess",f.rightRecess,"right",roots[f.level].trav],["left lateral recess",f.leftRecess,"left",roots[f.level].trav],["right foramen",f.rightForamen,"right",roots[f.level].exit],["left foramen",f.leftForamen,"left",roots[f.level].exit],["central canal",f.central,"bilateral","multiroot"]];for(const [zone,s,side,root] of zones){if(sev(s)===0)continue;let score=sev(s)*18;const yes:string[]=[];const no:string[]=[];if(i.side===side||i.side==="bilateral"||side==="bilateral"){score+=18;yes.push("Laterality is compatible")}else{score-=20;no.push("Laterality conflicts")};if(root!=="multiroot"){const sensory=(side==="right"?i.rightSensoryRoot:i.leftSensoryRoot);if(sensory===root){score+=12;yes.push("Sensory distribution supports the root")};const knee=grade(side==="right"?i.rightKneeExtension:i.leftKneeExtension), ankle=grade(side==="right"?i.rightAnkleDorsiflexion:i.leftAnkleDorsiflexion), toe=grade(side==="right"?i.rightGreatToeExtension:i.leftGreatToeExtension), plantar=grade(side==="right"?i.rightPlantarFlexion:i.leftPlantarFlexion);const motorSupport=(root==="L4"&&knee!==null&&knee<5)||(root==="L5"&&((ankle!==null&&ankle<5)||(toe!==null&&toe<5)||i.heelWalkAbnormal))||(root==="S1"&&((plantar!==null&&plantar<5)||i.toeWalkAbnormal||i.repeatedHeelRaiseAbnormal));if([knee,ankle,toe,plantar].every(x=>x===null))no.push("Motor examination unavailable");if(motorSupport){score+=12;yes.push("Motor examination supports the root")};if((root==="L5"||root==="S1")&&i.straightLegRaise==="positive"){score+=6;yes.push("Straight-leg raise supports a lower-lumbar root pattern")};if((root==="L2"||root==="L3"||root==="L4")&&i.femoralStretch==="positive"){score+=6;yes.push("Femoral stretch supports an upper-lumbar root pattern")}}else{if(i.painPattern==="claudication"||i.side==="bilateral"){score+=14;yes.push("Central/multiroot syndrome is compatible")}else{no.push("Single-root symptoms may not fully explain central stenosis")}}if(i.hipExamAbnormal){score-=10;no.push("Abnormal hip examination is a competing source")};if(i.pulsesAbnormal){score-=12;no.push("Abnormal vascular examination is a competing source")};if(f.rootDeformation){score+=8;yes.push("Root deformation documented")};out.push({level:f.level,side,root,zone,score:Math.max(0,Math.min(100,score)),for:yes,against:no})}}return out.sort((a,b)=>b.score-a.score).slice(0,5)}
export function validateCase(i:CaseInput){const e:string[]=[];if(i.age!==null&&i.age<18)e.push("This treatment-reconciliation module is limited to adults; safety screening remains available.");return e}
export function safetyCompleteness(i:CaseInput){const fields=[i.progressiveWeaknessStatus,i.urinaryRetentionStatus,i.urinarySensationLossStatus,i.urinaryInitiationDifficultyStatus,i.overflowIncontinenceStatus,i.saddleAnesthesiaStatus,i.bilateralSevereDeficitStatus,i.feverStatus,i.cancerWarningStatus,i.traumaWarningStatus];return fields.every(x=>x==="present"||x==="absent")}
export function evaluateCase(i:CaseInput):DecisionOutput{
 const app=scope(i), neuro=neurologicSeverity(i), target=candidates(i), top=target[0]; const emergency=[i.urinaryRetentionStatus,i.urinarySensationLossStatus,i.overflowIncontinenceStatus,i.saddleAnesthesiaStatus,i.bilateralSevereDeficitStatus].includes("present")||(measured(i.postVoidResidualMl)&&i.postVoidResidualMl>=300&&i.urinaryInitiationDifficultyStatus==="present");const infection=i.feverStatus==="present"&&(i.bacteremiaOrRecentInfection||i.immunosuppression||i.recentProcedure);const cancer=i.cancerWarningStatus==="present";const fracture=i.traumaWarningStatus==="present";
 const progressive=i.progressiveWeaknessStatus==="present";const safetyComplete=safetyCompleteness(i);const urgency=emergency?"emergency":(progressive||infection||cancer||fracture)?"urgent":"routine";const urgencyReason=emergency?"One or more emergency warning findings are present. Follow the local emergency pathway immediately and obtain urgent clinical and imaging assessment.":progressive?"Progressive objective weakness warrants expedited specialist assessment.":infection||cancer||fracture?"Serious-pathology warning features require expedited diagnostic evaluation.":safetyComplete?"Required emergency features were documented as absent in the entered assessment. This does not independently exclude emergency pathology.":"Emergency assessment is incomplete. One or more required findings are unknown or not assessed; do not interpret this as a negative emergency screen.";
 const syndrome=i.painPattern==="not-assessed"?"Syndrome not assessed":i.painPattern==="claudication"?"Probable neurogenic claudication":i.painPattern==="radicular"?"Probable lumbar radiculopathy":i.painPattern==="mixed"?"Mixed radicular/claudicant syndrome":i.painPattern==="axial"?"Axial-predominant low-back pain":"Syndrome uncertain";
 let reconciliation:DecisionOutput["reconciliation"]="insufficient";if(top){reconciliation=top.for.length>=3&&top.against.length===0?"concordant":top.for.length>=1?"partially-concordant":"discordant"}
 const support:string[]=[];const contradictions:string[]=[];const missing:string[]=[];if(top) support.push(`Highest-ranked target: ${top.side} ${top.root} at ${top.level} ${top.zone}`,...top.for);if(top) contradictions.push(...top.against);if(i.age===null)missing.push("Age is not entered.");if(i.symptomDurationWeeks===null)missing.push("Symptom duration is not entered.");if(i.imageQuality!=="adequate")missing.push("Imaging quality is limited or unknown.");if(i.dynamicInstability==="unknown")missing.push("Dynamic instability is unknown.");if(i.examConfidence!=="high")missing.push("Neurologic examination confidence is not high.");if(measured(i.imagingAgeMonths)&&i.imagingAgeMonths>12)missing.push("Imaging is older than 12 months; determine whether it still represents current symptoms.");
 const alternatives:string[]=[];if(i.hipExamAbnormal||i.groinPain)alternatives.push("Hip pathology");if(i.pulsesAbnormal||i.reliefPattern==="stopping-only")alternatives.push("Vascular claudication");if(i.neuropathyFeatures)alternatives.push("Peripheral neuropathy");if(i.painPattern==="axial")alternatives.push("Facet, sacroiliac, discogenic, endplate, or nonspecific chronic low-back pain mechanisms");
 const diagnosticNextSteps:string[]=[];if(app.status!=="appropriate")diagnosticNextSteps.push("Use the appropriate specialty or emergency pathway because this case is outside or at the edge of the validated module scope.");if(!top||reconciliation==="discordant")diagnosticNextSteps.push("Reassess level, side, root, hip, vascular, and peripheral nerve localization before an invasive procedure.");if(i.imagingLevel==="multilevel")diagnosticNextSteps.push("Perform level-by-level clinical–imaging reconciliation; do not treat every abnormal level.");
 const nonoperativePathway:string[]=[];if(urgency==="routine")nonoperativePathway.push("Shared decision-making with activity modification and individualized exercise-based rehabilitation.","Medication strategy based on contraindications and prior response.");if(i.injectionResponse==="not-tried"&&i.painPattern!=="axial"&&reconciliation!=="discordant")nonoperativePathway.push("A targeted diagnostic/therapeutic injection may be considered; response does not independently prove the symptomatic level.");
 const surgicalDecision:string[]=[];const objectiveFinding=neuro==="moderate"||neuro==="severe"||i.straightLegRaise==="positive"||i.femoralStretch==="positive";const durableSymptoms=measured(i.symptomDurationWeeks)&&i.symptomDurationWeeks>=6;const minimumTargetEvidence=!!top&&top.for.length>=2&&top.against.length<=2&&i.levelByLevelDocumented&&i.actualImagesReviewed;if(app.status==="appropriate"&&urgency!=="emergency"&&minimumTargetEvidence&&(durableSymptoms||objectiveFinding))surgicalDecision.push("Specialist review support: Supported by concordant anatomy plus persistent symptoms or an objective finding; clinician confirmation remains required.");else if(app.status==="out-of-scope")surgicalDecision.push("Specialist review support: Unable to assess within the intended-use population.");else surgicalDecision.push("Specialist review support: Not established from the current information.");
 const independent=i.dynamicInstability==="present"||i.foraminalCollapse==="present"||i.plannedFacetResection==="substantial"||(i.deformityPresent&&(measured(i.coronalCobbDegrees)&&i.coronalCobbDegrees>=20||i.sagittalImbalancePresent));const fusionAssessment=independent&&minimumTargetEvidence?"An independent fusion rationale may be present, but it requires direct confirmation of instability, deformity, collapse, revision-related instability, or anticipated iatrogenic instability. Fusion is not supported merely by stenosis, back pain, prior surgery, facet disease, or a mild stable degenerative slip.":"Decompression-first reasoning is favored. No independent fusion rationale is established from the entered data.";
 const operativeOptions:string[]=[];if(top&&minimumTargetEvidence){operativeOptions.push(`Targeted decompression consideration at ${top.level}, ${top.side} ${top.zone}, addressing the ${top.root} root.`);if(i.imagingFinding==="disc")operativeOptions.push("Limited discectomy/microdiscectomy may be considered when disc morphology and symptoms are concordant.");if(i.imagingFinding==="foraminal"||i.imagingFinding==="extraforaminal")operativeOptions.push("Foraminotomy or far-lateral decompression may be considered based on direct image review and facet preservation.")}
 const optimization:string[]=[];
 const nicotine=i.smoking||i.smokingStatus==="current"||i.vapingNicotine||i.smokelessTobacco||i.nicotineReplacement;
 if(nicotine)optimization.push("Current nicotine exposure: document cessation plan, timing, and institutional verification requirements before fusion.");
 if(i.diabetes&&(!measured(i.a1c)||i.a1cDate===""))optimization.push("Diabetes present but a current HbA1c is unavailable."); else if(i.diabetes&&measured(i.a1c)&&i.a1c>=8)optimization.push("Elevated HbA1c: optimize glycemic control using the procedure-specific institutional pathway.");
 if(i.anemia||measured(i.hemoglobin)&&i.hemoglobin<12)optimization.push("Anemia or low hemoglobin: evaluate cause and treat before elective surgery when feasible.");
 if(measured(i.albumin)&&i.albumin<3.5||i.recentWeightLoss)optimization.push("Nutrition concern: assess malnutrition and recent unintended weight loss.");
 if(i.boneHealth==="osteoporosis"||i.osteoporosisRisk||i.priorFragilityFracture||measured(i.dexLowestTScore)&&i.dexLowestTScore<=-2.5)optimization.push("Bone-health concern: complete procedure-specific bone optimization before instrumentation.");
 if(i.chronicOpioidUse||measured(i.opioidMmed)&&i.opioidMmed>0)optimization.push("Preoperative opioid exposure: document MME, prescriber, expectations, and perioperative analgesic plan.");
 if(i.sleepApnea&&!i.cpapUse)optimization.push("Obstructive sleep apnea with no documented CPAP use/adherence requires perioperative review.");
 if(i.anticoagulation)optimization.push("Create a coordinated anticoagulant/antiplatelet interruption and resumption plan.");
 const riskSummary:string[]=[];
 if(i.frailty==="moderate"||i.frailty==="severe"||measured(i.clinicalFrailtyScale)&&i.clinicalFrailtyScale>=5)riskSummary.push("Frailty-related perioperative vulnerability is elevated.");
 if(i.cardiopulmonaryDisease||i.coronaryDisease||i.heartFailure||i.copd||i.sleepApnea)riskSummary.push("Cardiopulmonary comorbidity requires formal procedure- and anesthesia-specific assessment.");
 if(i.kidneyDiseaseStage==="4"||i.kidneyDiseaseStage==="5"||i.kidneyDiseaseStage==="dialysis"||i.liverDisease)riskSummary.push("Advanced renal or hepatic disease may increase perioperative medical risk.");
 if(i.priorDvtPe)riskSummary.push("Prior DVT/PE requires individualized thrombosis and bleeding planning.");
 if(i.plannedRevision||i.sameLevelRevision||i.priorDuralTear||i.priorInfection||i.priorPseudarthrosis)riskSummary.push("Revision history or prior surgical complication increases technical complexity and limits generalizability of routine estimates.");
 if(i.plannedProcedure==="not-selected")riskSummary.push("A proposed procedure has not been selected; procedure-specific risk cannot be characterized.");
 riskSummary.push("No individualized complication percentage is calculated. These are evidence-informed flags pending calibration on real outcomes data.");
 const goalAligned=i.treatmentPreference==="nonoperative"&&surgicalDecision[0].startsWith("Specialist")?"The current surgical-consultation pathway may not align with the stated preference for nonoperative care; use shared decision-making.":`The proposed pathway should be discussed in relation to the goal: ${i.patientGoal}`;
 const ruleTrace:RuleTrace[]=[{ruleId:"SAFE-001",finding:urgencyReason,basis:"Emergency neurologic and serious-pathology screen",strength:"consensus"},{ruleId:"LOC-001",finding:top?`Candidate ${top.root} target at ${top.level}`:"No target established",basis:"Level, zone, side, motor, sensory, reflex, and competing-source reconciliation",strength:"moderate"},{ruleId:"FUS-001",finding:fusionAssessment,basis:"Decompression-first interpretation for many patients with stenosis and low-grade degenerative slip",strength:"high"},{ruleId:"SCOPE-001",finding:`Applicability: ${app.status}`,basis:"Prespecified intended-use population and exclusions",strength:"consensus"}];
 const checks=[{label:"Intended-use population",status:app.status==="appropriate"?"met":app.status==="limited"?"review":"missing",rationale:app.reasons.join("; ")||"Within the initial degenerative lumbar scope."},{label:"Direct image review",status:i.actualImagesReviewed?"met":"missing",rationale:"The tool must not replace direct image review."},{label:"Level-by-level matrix",status:i.levelByLevelDocumented?"met":"missing",rationale:"Multilevel abnormalities require zone- and side-specific review."},{label:"Patient goal and preference",status:i.patientGoal&&i.treatmentPreference?"met":"missing",rationale:"Treatment decisions should incorporate goals and preference."}] as DecisionOutput["checks"];
 return {urgency,urgencyReason,syndrome,neurologicSeverity:neuro,reconciliation,reconciliationNarrative:top?`The highest-ranked structured target is ${top.side} ${top.root} at ${top.level} ${top.zone}. This is a reconciliation result, not a confirmed diagnosis.`:"No level-root target could be established.",applicability:app,candidateTargets:target,support,contradictions,missing,alternatives,diagnosticNextSteps,nonoperativePathway,surgicalDecision,fusionAssessment,operativeOptions,surgicalPrerequisites:["Direct review of current imaging","Confirmation of side, root, and functional deficit","Patient-centered discussion of alternatives and expectations","Separate medical and anesthetic risk assessment"],operativeRisks:["Dural tear","Neural injury","Infection","Persistent or recurrent symptoms","Reoperation","Instability after decompression when relevant"],optimization,patientGoalAlignment:goalAligned,riskSummary,ruleTrace,evidenceIds:["NASS-LDH","NASS-LSS","NORDSTEN-5Y","SWEDISH-LSS","ACR-LBP","CES-PATH","CNS-RISK"],checks}
}
