export type ClinicalStatus = "present" | "absent" | "unknown" | "not-assessed";
export type Confidence = "high" | "moderate" | "low" | "not-assessed";
export type Laterality = "right" | "left" | "bilateral" | "midline" | "not-assessed";
export type Root = "L4" | "L5" | "S1";
export type RootOrNone = Root | "multiroot" | "none" | "not-assessed";
export type LumbarLevel = "L1-2" | "L2-3" | "L3-4" | "L4-5" | "L5-S1";
export type Zone = "central" | "right-recess" | "left-recess" | "right-foramen" | "left-foramen";
export type Severity = "none" | "mild" | "moderate" | "severe" | "not-graded";
export type MotorGrade = "5" | "4+" | "4" | "3" | "2" | "1" | "0" | "not-tested";
export type Reflex = "normal" | "reduced" | "absent" | "brisk" | "not-tested";
export type Measurement = { value: number | null; status: "measured" | "not-measured" | "unknown" | "not-applicable"; date?: string; unit?: string };

export type LevelFinding = {
  level: LumbarLevel;
  central: Severity;
  rightRecess: Severity;
  leftRecess: Severity;
  rightForamen: Severity;
  leftForamen: Severity;
  discMorphology: "none" | "bulge" | "protrusion" | "extrusion" | "sequestration" | "not-assessed";
  migration: "none" | "cranial" | "caudal" | "not-assessed";
  synovialCyst: ClinicalStatus;
  rootDeformation: ClinicalStatus;
  priorDecompression: ClinicalStatus;
};

export type FusionLevelFinding = {
  level: LumbarLevel;
  dynamicInstability: ClinicalStatus;
  translationMm: Measurement;
  angularMotionDeg: Measurement;
  foraminalCollapse: ClinicalStatus;
  plannedFacetResectionPercent: Measurement;
  revisionDestabilization: ClinicalStatus;
  pseudarthrosis: ClinicalStatus;
  relevantDeformity: ClinicalStatus;
};

export type CaseInput = {
  studyId: string;
  age: Measurement;
  sexAtBirth: "female" | "male" | "intersex" | "unknown";
  symptomDurationWeeks: Measurement;
  side: Laterality;
  clinicianPhenotype: "radicular" | "claudication" | "axial" | "mixed" | "uncertain" | "not-assessed";
  clinicianSuspectedRoot: RootOrNone;
  backPainNrs: Measurement;
  legPainNrs: Measurement;
  walkingLimitMeters: Measurement;
  patientGoal: string;
  treatmentPreference: "nonoperative" | "open-to-surgery" | "undecided" | "not-assessed";

  legDominantPain: ClinicalStatus;
  dermatomalPain: ClinicalStatus;
  standingProvokes: ClinicalStatus;
  walkingProvokes: ClinicalStatus;
  sittingRelieves: ClinicalStatus;
  flexionRelieves: ClinicalStatus;
  stoppingAloneRelieves: ClinicalStatus;
  bicycleBetter: ClinicalStatus;
  uphillBetterThanDownhill: ClinicalStatus;
  legHeaviness: ClinicalStatus;
  coughSneezeProvokes: ClinicalStatus;
  groinPain: ClinicalStatus;

  rightKneeExtension: MotorGrade;
  leftKneeExtension: MotorGrade;
  rightAnkleDorsiflexion: MotorGrade;
  leftAnkleDorsiflexion: MotorGrade;
  rightGreatToeExtension: MotorGrade;
  leftGreatToeExtension: MotorGrade;
  rightPlantarFlexion: MotorGrade;
  leftPlantarFlexion: MotorGrade;
  weaknessQuality: "true" | "pain-limited" | "give-way" | "uncertain" | "not-assessed";
  weaknessTrajectory: "stable" | "progressive" | "improving" | "none" | "not-assessed";
  weaknessProgressionBasis: "patient-reported" | "clinician-concern" | "serial-objective" | "not-assessed";
  examConfidence: Confidence;
  muscleAtrophy: ClinicalStatus;
  heelWalkAbnormal: ClinicalStatus;
  toeWalkAbnormal: ClinicalStatus;
  repeatedHeelRaiseAbnormal: ClinicalStatus;
  rightPatellarReflex: Reflex;
  leftPatellarReflex: Reflex;
  rightAchillesReflex: Reflex;
  leftAchillesReflex: Reflex;
  rightSensoryRoot: RootOrNone | "non-dermatomal" | "not-tested";
  leftSensoryRoot: RootOrNone | "non-dermatomal" | "not-tested";
  straightLegRaise: "positive" | "negative" | "not-tested";
  femoralStretch: "positive" | "negative" | "not-tested";
  hipExamAbnormal: ClinicalStatus;
  pulsesAbnormal: ClinicalStatus;
  neuropathyFeatures: ClinicalStatus;

  urinaryRetention: ClinicalStatus;
  urinarySensationLoss: ClinicalStatus;
  urinaryInitiationDifficulty: ClinicalStatus;
  overflowIncontinence: ClinicalStatus;
  urinaryUrgencyAlone: ClinicalStatus;
  saddleSensoryChange: ClinicalStatus;
  bilateralSevereDeficit: ClinicalStatus;
  progressiveWeakness: ClinicalStatus;
  feverOrSystemicInfection: ClinicalStatus;
  cancerWarning: ClinicalStatus;
  traumaOrFractureWarning: ClinicalStatus;

  imagesReviewed: ClinicalStatus;
  imageQuality: "adequate" | "limited" | "unknown" | "not-assessed";
  imagingAgeMonths: Measurement;
  levelByLevelDocumented: ClinicalStatus;
  imagingMatrix: LevelFinding[];
  fusionMatrix: FusionLevelFinding[];

  exerciseProgramCompleted: ClinicalStatus;
  exerciseWeeks: Measurement;
  medicationTrialCompleted: ClinicalStatus;
  injectionResponse: "not-tried" | "none" | "brief" | "meaningful-temporary" | "sustained" | "unknown";
  injectionLevel: LumbarLevel | "unknown" | "not-applicable";
  injectionSide: Laterality;

  smokingStatus: "never" | "former" | "current" | "not-assessed";
  nicotineVaping: ClinicalStatus;
  smokelessTobacco: ClinicalStatus;
  diabetesType: "none" | "type-1" | "type-2" | "other" | "not-assessed";
  hba1c: Measurement;
  bmi: Measurement;
  hemoglobin: Measurement;
  albumin: Measurement;
  frailtyScale: Measurement;
  boneHealth: "normal" | "osteopenia" | "osteoporosis" | "unknown" | "not-assessed";
  dexTScore: Measurement;
  fragilityFracture: ClinicalStatus;
  chronicOpioidUse: ClinicalStatus;
  opioidMme: Measurement;
  sleepApnea: ClinicalStatus;
  cpapAdherent: ClinicalStatus;
  anticoagulation: ClinicalStatus;
  priorDvtPe: ClinicalStatus;
  cardiopulmonaryDisease: ClinicalStatus;
  advancedRenalOrLiverDisease: ClinicalStatus;
  priorSurgeryType: "none" | "decompression" | "discectomy" | "fusion" | "multiple" | "not-assessed";
  sameLevelRevision: ClinicalStatus;
  priorDuralTear: ClinicalStatus;
  priorInfection: ClinicalStatus;
  priorPseudarthrosis: ClinicalStatus;

  proposedProcedure: "none" | "decompression" | "discectomy" | "fusion" | "decompression-fusion" | "other" | "not-assessed";
  proposedLevels: LumbarLevel[];
  plannedSetting: "outpatient" | "inpatient" | "not-assessed";

  pediatric: ClinicalStatus;
  pregnant: ClinicalStatus;
  cervicalThoracicSymptoms: ClinicalStatus;
  neuromuscularDisease: ClinicalStatus;
  knownTumor: ClinicalStatus;
  knownInfection: ClinicalStatus;
  acuteFracture: ClinicalStatus;
  majorDeformity: ClinicalStatus;
  priorLongFusion: ClinicalStatus;
  predominantlyAxialPain: ClinicalStatus;
};

export type ReviewerAssessment = {
  reviewerId: string;
  specialty: "spine-surgery" | "pmr" | "pain" | "radiology" | "other" | "not-entered";
  syndrome: "radiculopathy" | "claudication" | "mixed" | "axial" | "indeterminate" | "not-entered";
  side: Laterality | "not-entered";
  root: RootOrNone | "not-entered";
  level: LumbarLevel | "multilevel" | "none" | "not-entered";
  zone: Zone | "multilevel" | "none" | "not-entered";
  urgency: "emergency" | "urgent" | "routine" | "indeterminate" | "not-entered";
  additionalTesting: "yes" | "no" | "indeterminate" | "not-entered";
  specialistReviewSupport: "supported" | "not-established" | "unable-to-assess" | "not-entered";
  decompressionTarget: string;
  fusionRationale: "established" | "possible" | "not-established" | "unable-to-assess" | "not-entered";
  confidence: Confidence;
  rationale: string;
};

export type AdjudicationRecord = {
  caseId: string;
  siteCode: string;
  firstReviewer: ReviewerAssessment;
  secondReviewer: ReviewerAssessment;
  adjudicated: ReviewerAssessment;
  adjudicationMethod: "unanimous" | "majority" | "third-reviewer" | "consensus-meeting" | "not-entered";
  disagreementReason: string;
  actualTreatment: string;
  procedurePerformed: string;
  operativeLevels: string;
  outcomeVisibleDuringAdjudication: false;
  anyThirtyDayComplication: "yes" | "no" | "unknown";
  majorMedicalComplication: "yes" | "no" | "unknown";
  surgicalSiteInfection: "yes" | "no" | "unknown";
  neurologicDeterioration: "yes" | "no" | "unknown";
  duralTear: "yes" | "no" | "unknown";
  ninetyDayReadmission: "yes" | "no" | "unknown";
  ninetyDayReoperation: "yes" | "no" | "unknown";
  nonHomeDischarge: "yes" | "no" | "unknown";
  sixMonthOdi: Measurement;
  twelveMonthOdi: Measurement;
  sixMonthLegPain: Measurement;
  twelveMonthLegPain: Measurement;
  sixMonthBackPain: Measurement;
  twelveMonthBackPain: Measurement;
  sixMonthPromisPf: Measurement;
  twelveMonthPromisPf: Measurement;
  notes: string;
};
