// Merges duplicate selector declarations outside media queries, in source order.
// Property-level merge preserves the original cascade exactly for equal specificity.
import { readFileSync, writeFileSync } from "node:fs";
const src = readFileSync("app/globals.css", "utf8");
const tokens = []; let i = 0; const n = src.length;
while (i < n) {
  if (src.startsWith("@", i)) {
    const j = src.indexOf("{", i); let d = 1, k = j + 1;
    while (d && k < n) { if (src[k] === "{") d++; else if (src[k] === "}") d--; k++; }
    tokens.push(["at", src.slice(i, k)]); i = k;
  } else {
    const m = /([^{}@]+)\{([^{}]*)\}/y; m.lastIndex = i;
    const r = m.exec(src);
    if (r) { tokens.push(["rule", r[1].trim(), r[2].trim()]); i = m.lastIndex; } else i++;
  }
}
const order = [], merged = new Map(), at = [];
for (const t of tokens) {
  if (t[0] !== "rule") { at.push(t[1]); continue; }
  for (const sel of t[1].split(",").map(x => x.trim()).filter(Boolean)) {
    if (!merged.has(sel)) { merged.set(sel, new Map()); order.push(sel); }
    for (const d of t[2].split(";")) {
      const idx = d.indexOf(":");
      if (idx < 0) continue;
      merged.get(sel).set(d.slice(0, idx).trim(), d.slice(idx + 1).trim());
    }
  }
}
const out = [
  "/* SpineDx-Tx consolidated stylesheet — generated by scripts/consolidate-css.mjs.",
  "   One declaration per selector outside media queries. Run after editing to re-flatten. */",
  "",
  ...order.map(sel => `${sel}{${[...merged.get(sel)].map(([k, v]) => `${k}:${v}`).join(";")}}`),
  "",
  "/* Responsive and print scopes — intentionally separate. */",
  ...at,
];
writeFileSync("app/globals.css", out.join("\n") + "\n");
console.log(`consolidated: ${order.length} selectors, ${at.length} at-rule blocks`);
